# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-app
  namespace: cloudops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudops-app
  template:
    metadata:
      labels:
        app: cloudops-app
    spec:
      containers:
        - name: cloudops-app
          image: devilzz/cloudops-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cloudops-config
            - secretRef:
                name: cloudops-secret