apiVersion: v1
kind: Service
metadata:
  name: cloudops-service
  namespace: cloudops
spec:
  type: NodePort
  selector:
    app: cloudops-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
