# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cloudops-service
  namespace: cloudops
spec:
  type: LoadBalancer
  selector:
    app: cloudops-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP