apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alert-rules.yaml: |
    groups:
    - name: kubernetes-alerts
      rules:

      # ðŸ”´ ALERT 1 â€” Deployment exists but no pods available
      - alert: CloudOpsDeploymentUnavailable
        expr: |
          kube_deployment_spec_replicas{namespace="cloudops",deployment="cloudops-app"} > 0
          AND
          kube_deployment_status_replicas_available{namespace="cloudops",deployment="cloudops-app"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: CloudOps deployment unavailable
          description: "Deployment cloudops-app has desired replicas but zero available for 30+ seconds"

      # ðŸ”´ ALERT 2 â€” Deployment missing
      - alert: CloudOpsDeploymentMissing
        expr: |
          absent(kube_deployment_spec_replicas{namespace="cloudops",deployment="cloudops-app"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: CloudOps deployment missing
          description: "cloudops-app deployment does not exist in the cluster"

      # ðŸ”´ ALERT 3 â€” ImagePullBackOff / ErrImagePull
      - alert: CloudOpsImagePullFailure
        expr: |
          kube_pod_container_status_waiting_reason{
            namespace="cloudops",
            reason=~"ImagePullBackOff|ErrImagePull"
          } == 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: Image pull failure
          description: "Pod container in cloudops namespace is failing to pull image"

      # ðŸŸ  ALERT 4 â€” High CPU Usage (per pod, in cloudops)
      - alert: HighCPUUsage
        expr: |
         sum by (namespace, pod) (
            rate(container_cpu_usage_seconds_total{
              namespace="cloudops",
              container!="",
              image!=""
            }[2m])
          ) > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: Pod {{ $labels.pod }} CPU > 0.8 cores for 2 minutes


      # ðŸŸ  ALERT 5 â€” High Memory Usage (working set, per pod, in cloudops)
      - alert: HighMemoryUsage
        expr: |
          sum by (namespace, pod) (
            container_memory_working_set_bytes{
              namespace="cloudops",
              container!="",
              image!=""
            }
          ) > 500000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Pod {{ $labels.pod }} using > 500MB memory


      # ðŸŸ  ALERT 6 â€” Container Restarting
      - alert: ContainerRestarting
        expr: |
          increase(kube_pod_container_status_restarts_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Container restarting
          description: "Pod {{ $labels.pod }} container {{ $labels.container }} restarted in the last 5 minutes"
