apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alert-rules.yaml: |
    groups:
    - name: kubernetes-alerts
      rules:

      # ğŸ”´ ALERT 1 â€” Deployment exists but no pods available
      - alert: CloudOpsDeploymentUnavailable
        expr: |
          kube_deployment_spec_replicas{namespace="cloudops",deployment="cloudops-app"} > 0
          AND
          kube_deployment_status_replicas_available{namespace="cloudops",deployment="cloudops-app"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: CloudOps deployment unavailable
          description: Deployment exists but has zero available replicas for 30 seconds.

      # ğŸ”´ ALERT 2 â€” Deployment missing (deleted / not created)
      - alert: CloudOpsDeploymentMissing
        expr: |
          absent(kube_deployment_spec_replicas{namespace="cloudops",deployment="cloudops-app"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: CloudOps deployment missing
          description: cloudops-app deployment does not exist in the cluster.

      # ğŸŸ  CPU alert
      - alert: HighCPUUsage
        expr: |
          sum(rate(container_cpu_usage_seconds_total{container!="",pod!=""}[2m])) by (pod) > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: CPU usage is above 80 percent for more than 2 minutes.

      # ğŸŸ  Memory alert
      - alert: HighMemoryUsage
        expr: |
          container_memory_usage_bytes > 500000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Memory usage is above threshold.

      # ğŸŸ  Restart alert
      - alert: ContainerRestarting
        expr: |
          increase(kube_pod_container_status_restarts_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Container restarting
          description: A container restarted in the last 5 minutes.
